services:
  - type: web
    name: hishabpati
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        sync: false