spring.application.name=HishabPati
spring.mongodb.database=hishabpati_db
spring.mongodb.uri=mongodb+srv://sifatmazib526_db_user:LjTvpblmB6pXwyS0@mongo-sifat.2ro3hua.mongodb.net/?appName=mongo-sifat
server.port=8080
server.address=0.0.0.0

